CREATE DATABASE DCIDB;
USE DCIDB;

CREATE TABLE VENDORS(
	VENDORID INT IDENTITY(1,1) PRIMARY KEY,
	VENDORNAME VARCHAR(50),
	PHONENUMBER VARCHAR(10),
	EMAIL VARCHAR(50)
);

CREATE TABLE PRODUCTS(
	PRODUCTID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCTNAME VARCHAR(50) NOT NULL,
	SKU VARCHAR(12) UNIQUE,
	UPC VARCHAR(12),
	CATEGORY VARCHAR(25),
	PRODUCTDESCRIPTION VARCHAR(MAX),
	VENDORID INT,
	CONSTRAINT CATEGORY_CHK CHECK (CATEGORY IN ('MISC', 'FOOD/DRINK', 'PLUMBING', 'HARDWARE', 'APPLICANCE')),
	CONSTRAINT PRODUCTS_VENDORID FOREIGN KEY (VENDORID) REFERENCES VENDORS(VENDORID)
);

CREATE TABLE VENDORTRANSACTION(
	TRANSACTIONID INT IDENTITY(1,1) PRIMARY KEY,
	PRODUCTID INT NOT NULL,
	VENDORID INT NOT NULL,
	UNITSSOLD INT DEFAULT 0,
	TRANSACTIONDATE DATE DEFAULT GETDATE(),
	CONSTRAINT VT_PRODUCTID FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(PRODUCTID),
	CONSTRAINT VT_VENDORID FOREIGN KEY (VENDORID) REFERENCES VENDORS(VENDORID)
);

CREATE TABLE LOCATIONS(
	LOCATIONID INT IDENTITY(1,1) PRIMARY KEY,
	ADDRESS VARCHAR(100) NOT NULL,
	ZIPCODE VARCHAR(5) NOT NULL,
	STATE CHAR(2) NOT NULL,
	LOCATIONTYPE VARCHAR(10) NOT NULL,
	CONSTRAINT LOCATIONTYPE_CHK CHECK (LOCATIONTYPE IN ('WAREHOUSE','CUSTOMER','STORES'))
);

CREATE TABLE DELIVERY(	
	DELIVERYID INT IDENTITY(1,1) PRIMARY KEY,
	SOURCELOCATION INT NOT NULL,
	DESTINATIONLOCATION INT NOT NULL,
	PRODUCTID INT NOT NULL,
	UNITS INT NOT NULL,
	DELIVERYSTATUS VARCHAR(25) NOT NULL,
	DATEDELIVERED DATE DEFAULT GETDATE(),
	TRACKINGCODE VARCHAR(18) DEFAULT NULL,
	CONSTRAINT DELIVERYSTATUS_CHK CHECK (DELIVERYSTATUS IN ('DELIVERED','EN ROUTE')), 
	CONSTRAINT DELIVERY_SOURCE FOREIGN KEY (SOURCELOCATION) REFERENCES LOCATIONS(LOCATIONID),
	CONSTRAINT DELIVERY_DESTINATION FOREIGN KEY (DESTINATIONLOCATION) REFERENCES LOCATIONS(LOCATIONID)
);


CREATE TABLE WAREHOUSES(
	WAREHOUSEID INT IDENTITY(1,1) PRIMARY KEY,
	LOCATIONID INT NOT NULL,
	CONSTRAINT WAREHOUSES_LOCATION FOREIGN KEY (LOCATIONID) REFERENCES LOCATIONS(LOCATIONID)
);

CREATE TABLE CUSTOMERS(
	CUSTOMERID INT IDENTITY(1,1) PRIMARY KEY,
	LOCATIONID INT NOT NULL,
	FIRSTNAME VARCHAR(20) NOT NULL,
	LASTNAME VARCHAR(20) NOT NULL,
	GENDER VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(50),
	PHONENUMBER VARCHAR(10),
	CONSTRAINT GENDER_CHK CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
	CONSTRAINT CUSTOMERS_LOCATION FOREIGN KEY (LOCATIONID) REFERENCES LOCATIONS(LOCATIONID)
);

CREATE TABLE STORES(
	STOREID INT IDENTITY(1,1),
	LOCATIONID INT NOT NULL,
	MANAGERNAME VARCHAR(30),
	CONSTRAINT STORES_LOCATION FOREIGN KEY (LOCATIONID) REFERENCES LOCATIONS(LOCATIONID)
);